/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.MovieManufacture;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JPanel;

/**
 *
 * @author HH
 */
public class CostumeManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LightingWorkAreaJPanel
     */
    private JPanel card;
    private Enterprise enterprise;
    private EcoSystem business;
    private UserAccount userAccount;
    public CostumeManagerWorkAreaJPanel(JPanel card,EcoSystem business,UserAccount userAccount,Enterprise enterprise) {
        initComponents();
        this.card=card;
        this.business=business;
        this.enterprise=enterprise;
        this.userAccount=userAccount;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewStaffButton = new javax.swing.JButton();
        managercostumeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1 = new JPanel (){
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                Image img=Toolkit.getDefaultToolkit().getImage("bgfilm.png");
                g.drawImage(img, 0, 0, this.getParent().getWidth(), this.getParent().getHeight(), this);
            }
        };

        viewStaffButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewStaffButton.setText("View staff list");
        viewStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStaffButtonActionPerformed(evt);
            }
        });

        managercostumeButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        managercostumeButton.setText("Manage costume");
        managercostumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managercostumeButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Costume Work Area");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(managercostumeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewStaffButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(309, 309, 309))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(viewStaffButton)
                .addGap(148, 148, 148)
                .addComponent(managercostumeButton)
                .addGap(162, 162, 162))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStaffButtonActionPerformed
          CostumeViewStaffPanel panel=new CostumeViewStaffPanel(card, business, userAccount, enterprise);
          card.add("CostumeViewStaffPanel",panel);
          CardLayout layout=(CardLayout)card.getLayout();
          layout.next(card);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewStaffButtonActionPerformed

    private void managercostumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managercostumeButtonActionPerformed
        // TODO add your handling code here:
        CostumeManageJPanel manage=new CostumeManageJPanel(card, business, userAccount, enterprise);
          card.add("CostumeManageJPanel",manage);
          CardLayout layout=(CardLayout)card.getLayout();
          layout.next(card);
    }//GEN-LAST:event_managercostumeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton managercostumeButton;
    private javax.swing.JButton viewStaffButton;
    // End of variables declaration//GEN-END:variables
}
