/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.MovieManufacture;

import Business.Enterprise.Enterprise;
import javax.swing.JPanel;
import Business.EcoSystem;
import Business.Enterprise.SponsorEnterprise;
import Business.Movie.Movie;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.SponsorManagerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RequestForSponsorship;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HH
 */
public class DirectorRequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form DirectoryWorkAreaJPanel
     */
    private EcoSystem business;
    private JPanel card;
    private UserAccount userAccount;
    private Enterprise enterprise;
    public DirectorRequestPanel(JPanel card,EcoSystem business,UserAccount userAccount,Enterprise enterprise) {
        initComponents();
        this.card=card;
        this.business=business;
        this.userAccount=userAccount;
        this.enterprise=enterprise;
        populateSponsorCombox();
        populateMovieCombox();
        populateRequestTable2();
    }
    
    public void populateMovieCombox(){
        movieCombox.removeAllItems();
        for(Movie movie:userAccount.getMovielist().getMovieList()){
            movieCombox.addItem(movie);
        }
    }

    
    public void populateSponsorCombox(){
        sponsorCombox.removeAllItems();
        for(Network network:business.getNetworkslist()){
            for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseslist()){
                if(enterprise instanceof SponsorEnterprise){
                    sponsorCombox.addItem(enterprise);
                }
            }
        }
    }
    

    
    public void populateRequestTable2(){
        DefaultTableModel dtm=(DefaultTableModel)requestTable.getModel();
        dtm.setRowCount(0);
        for(WorkRequest request:userAccount.getWorkQueue().getWorkRequestList()){
            if(request instanceof RequestForSponsorship){
            RequestForSponsorship request2=(RequestForSponsorship)request;
            Object row[]=new Object[4];
            row[0]=request2;
            row[1]=request2.getReceiver();
            row[2]=request2.getStatus();
            row[3]=request2.getMovie().getBudget();
            dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        requestButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        movieCombox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        sponsorCombox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        budgetText = new javax.swing.JTextField();
        selectStaffButton1 = new javax.swing.JButton();

        jPanel1 = new JPanel (){
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                Image img=Toolkit.getDefaultToolkit().getImage("bgfilm.png");
                g.drawImage(img, 0, 0, this.getParent().getWidth(), this.getParent().getHeight(), this);
            }
        };

        backButton.setBackground(new java.awt.Color(153, 153, 153));
        backButton.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        requestTable.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie", "Receiver", "Status", "Budget"
            }
        ));
        jScrollPane1.setViewportView(requestTable);

        requestButton.setBackground(new java.awt.Color(153, 153, 153));
        requestButton.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        requestButton.setText("Request");
        requestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel1.setText("Movie");

        movieCombox.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        movieCombox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel2.setText("Sponsor");

        sponsorCombox.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        sponsorCombox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel3.setText("Expected Budget");

        budgetText.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        selectStaffButton1.setBackground(new java.awt.Color(153, 153, 153));
        selectStaffButton1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        selectStaffButton1.setText("Select Staff");
        selectStaffButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectStaffButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(backButton))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(169, 169, 169)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(movieCombox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(requestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sponsorCombox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(budgetText, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(selectStaffButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sponsorCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(movieCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(budgetText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(108, 108, 108)
                .addComponent(requestButton)
                .addGap(32, 32, 32)
                .addComponent(selectStaffButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestButtonActionPerformed

         Movie movie=(Movie)movieCombox.getSelectedItem();
         Enterprise e=(Enterprise)sponsorCombox.getSelectedItem();
         try{
             double expectedBudget=Double.parseDouble(budgetText.getText()); 
         RequestForSponsorship workrequest=new RequestForSponsorship();
         workrequest.setSender(userAccount);
         workrequest.setStatus("Sent");
         workrequest.setMovie(movie);
         workrequest.setEnterprise(e);
         workrequest.getMovie().setBudget(expectedBudget);
         userAccount.getWorkQueue().getWorkRequestList().add(workrequest);
         for(Network network:business.getNetworkslist()){
             for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseslist()){
                 if(enterprise instanceof SponsorEnterprise){
                     for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                         if(organization instanceof SponsorManagerOrganization){
                             organization.getWorkQueue().getWorkRequestList().add(workrequest);
                         }
                     }
                 }
             }
         }
         JOptionPane.showMessageDialog(null, "Request successfully!");
         populateRequestTable2();
         }
         catch(Exception ee){
             JOptionPane.showMessageDialog(null, "Please input a valid expected budget.");
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_requestButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
               card.remove(this);
               CardLayout layout=(CardLayout)card.getLayout();
               layout.previous(card);
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void selectStaffButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectStaffButton1ActionPerformed
        int selectedrow=requestTable.getSelectedRow();
        if(selectedrow<0){
            JOptionPane.showMessageDialog(null, "Please select an row first.");
            return;
        }
        RequestForSponsorship workRequest=(RequestForSponsorship)requestTable.getValueAt(selectedrow, 0);
        Movie movie=workRequest.getMovie();
        if(movie==null){
            JOptionPane.showMessageDialog(null, "Please select a movie first.");
            return;
        }
        SelectStaffPanel panel=new SelectStaffPanel(card,business,movie,enterprise,userAccount);
        card.add("SelectStaffPanel",panel);
        CardLayout layout=(CardLayout)card.getLayout();
        layout.next(card);

        // TODO add your handling code here:
    }//GEN-LAST:event_selectStaffButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField budgetText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox movieCombox;
    private javax.swing.JButton requestButton;
    private javax.swing.JTable requestTable;
    private javax.swing.JButton selectStaffButton1;
    private javax.swing.JComboBox sponsorCombox;
    // End of variables declaration//GEN-END:variables
}
