/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.MovieManufacture;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JPanel;

/**
 *
 * @author andyg
 */
public class DirectorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DirectorWorkAreaJPanel
     */
    private JPanel card;
    private EcoSystem business;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Organization organization;
    public DirectorWorkAreaJPanel(JPanel card,EcoSystem business,UserAccount userAccount,Enterprise enterprise,Organization organization) {
        initComponents();
        this.business=business;
        this.card=card;
        this.userAccount=userAccount;
        this.enterprise=enterprise;
        this.organization=organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RequestPanel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        sellCopyrightButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1 = new JPanel (){
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                Image img=Toolkit.getDefaultToolkit().getImage("bgfilm.png");
                g.drawImage(img, 0, 0, this.getParent().getWidth(), this.getParent().getHeight(), this);
            }
        };

        RequestPanel.setBackground(new java.awt.Color(153, 153, 153));
        RequestPanel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RequestPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sponsor1.png"))); // NOI18N
        RequestPanel.setText("Request for sponsorship");
        RequestPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestPanelActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/list.png"))); // NOI18N
        jButton1.setText("View my movie list");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sellCopyrightButton.setBackground(new java.awt.Color(153, 153, 153));
        sellCopyrightButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sellCopyrightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/copyright.png"))); // NOI18N
        sellCopyrightButton.setText("Sell copyright");
        sellCopyrightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellCopyrightButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/director1.png"))); // NOI18N
        jLabel1.setText("Director Work Area");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RequestPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addComponent(sellCopyrightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(jButton1)
                .addGap(66, 66, 66)
                .addComponent(RequestPanel)
                .addGap(65, 65, 65)
                .addComponent(sellCopyrightButton)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RequestPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestPanelActionPerformed
          DirectorRequestPanel panel=new DirectorRequestPanel(card, business, userAccount,enterprise);
          card.add("DirectorRequestPanel",panel);
          CardLayout layout=(CardLayout)card.getLayout();
          layout.next(card);
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestPanelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         ViewMyMoviePanel panel=new ViewMyMoviePanel(card,business,userAccount,enterprise);
          card.add("ViewMyMoviePanel",panel);
          CardLayout layout=(CardLayout)card.getLayout();
          layout.next(card);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sellCopyrightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellCopyrightButtonActionPerformed
           DirectorSellCopyrightPanel panel=new DirectorSellCopyrightPanel(card,business,userAccount,organization);
           card.add("DirectorSellCopyrightPanel",panel);
           CardLayout layout=(CardLayout)card.getLayout();
           layout.next(card);

// TODO add your handling code here:
    }//GEN-LAST:event_sellCopyrightButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RequestPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sellCopyrightButton;
    // End of variables declaration//GEN-END:variables
}
