/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Sponsor;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.MovieManufactureEnterprise;
import Business.Movie.Movie;
import Business.Network.Network;
import Business.Organization.DirectorOrganization;
import Business.Organization.FinancialOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RequestForFinancial;
import Business.WorkQueue.RequestForSponsorship;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HH
 */
public class ManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageWorkAreaJPanel
     */
    private JPanel card;
    private EcoSystem business;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    public ManagerWorkAreaJPanel(JPanel card,EcoSystem business,UserAccount userAccount,Organization organization,Enterprise enterprise) {
        initComponents();
        this.business=business;
        this.card=card;
        this.userAccount=userAccount;
        this.organization=organization;
        this.enterprise=enterprise;
        populateRequestTable();
    }

    public void populateRequestTable(){
        DefaultTableModel dtm=(DefaultTableModel)requestTable.getModel();
        dtm.setRowCount(0);
        for(Network network:business.getNetworkslist()){
            for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseslist()){
                if(enterprise instanceof MovieManufactureEnterprise){
                    for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                        if(organization instanceof DirectorOrganization){
                            for(UserAccount account:organization.getUserAccountDirectory().getUserAccountList()){
                                for(WorkRequest request:account.getWorkQueue().getWorkRequestList()){
                                    if(request instanceof RequestForSponsorship){
                                    RequestForSponsorship request2=(RequestForSponsorship)request;
                                    Object row[]=new Object[5];
                                    row[0]=request2;
                                    row[1]=request2.getSender();
                                    row[2]=request2.getMovie().getBudget();
                                    row[3]=request2.getReceiver();
                                    row[4]=request2.getStatus();
                                    dtm.addRow(row);
                                }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        approveButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();

        jPanel1 = new JPanel (){
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                Image img=Toolkit.getDefaultToolkit().getImage("sponsor.png");
                g.drawImage(img, 0, 0, this.getParent().getWidth(), this.getParent().getHeight(), this);
            }
        };

        requestTable.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie Name", "Sender", "Expected Budget", "Receiver", "Status"
            }
        ));
        jScrollPane1.setViewportView(requestTable);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Request Table");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Sponsor Manager Work Area");

        approveButton.setBackground(new java.awt.Color(153, 153, 153));
        approveButton.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        approveButton.setText("Approve");
        approveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveButtonActionPerformed(evt);
            }
        });

        viewButton.setBackground(new java.awt.Color(153, 153, 153));
        viewButton.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(viewButton)
                .addGap(79, 79, 79)
                .addComponent(approveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveButton)
                    .addComponent(viewButton))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveButtonActionPerformed
         int selectedrow=requestTable.getSelectedRow();
         if(selectedrow<0){
             JOptionPane.showMessageDialog(null, "Please select an row first.");
             return;
         }
         RequestForSponsorship request=(RequestForSponsorship)requestTable.getValueAt(selectedrow, 0);
         request.setStatus("Approved");
         request.setReceiver(userAccount);
         populateRequestTable();
         RequestForFinancial request2=new RequestForFinancial();
         request2.setMovie(request.getMovie());
         request2.setSender(userAccount);
         request2.setStatus("Sent");
         userAccount.getWorkQueue().getWorkRequestList().add(request2);
         for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
            if(organization instanceof FinancialOrganization){
                for(UserAccount account:organization.getUserAccountDirectory().getUserAccountList()){
                        account.getWorkQueue().getWorkRequestList().add(request2);
                }
            }
        }
         JOptionPane.showMessageDialog(null, "Approved successfully.");
         
        
        // TODO add your handling code here:
    }//GEN-LAST:event_approveButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
         int selectedrow=requestTable.getSelectedRow();
         if(selectedrow<0){
             JOptionPane.showMessageDialog(null, "Please select an row first.");
             return;
         }
         RequestForSponsorship request=(RequestForSponsorship)requestTable.getValueAt(selectedrow, 0);
         Movie movie=request.getMovie();
         SponsorViewPanel panel=new SponsorViewPanel(card, business, userAccount, movie);
         card.add("SponsorViewPanel",panel);
         CardLayout layout=(CardLayout)card.getLayout();
         layout.next(card);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable requestTable;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
