/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Theater;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JPanel;

/**
 *
 * @author andyg
 */
public class ManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagerWorkAreaJPanel
     */
    private EcoSystem business;
    private JPanel card;
    private UserAccount userAccount;
    public ManagerWorkAreaJPanel(JPanel card,EcoSystem business,UserAccount userAccount) {
        initComponents();
        this.card=card;
        this.business=business;
        this.userAccount=userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        copyrightButton = new javax.swing.JButton();
        screenButton = new javax.swing.JButton();

        jPanel1 = new JPanel (){
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                Image img=Toolkit.getDefaultToolkit().getImage("theater.png");
                g.drawImage(img, 0, 0, this.getParent().getWidth(), this.getParent().getHeight(), this);
            }
        };

        copyrightButton.setBackground(new java.awt.Color(153, 153, 153));
        copyrightButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        copyrightButton.setText("Buy Movie Copyright");
        copyrightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyrightButtonActionPerformed(evt);
            }
        });

        screenButton.setBackground(new java.awt.Color(153, 153, 153));
        screenButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        screenButton.setText("Arrange the screening");
        screenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(screenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(copyrightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(289, 289, 289))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(copyrightButton)
                .addGap(159, 159, 159)
                .addComponent(screenButton)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void copyrightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyrightButtonActionPerformed
         BuyCopyrightJPanel panel=new BuyCopyrightJPanel(card, business, userAccount);
         card.add("BuyCopyrightJPanel",panel);
         CardLayout layout=(CardLayout)card.getLayout();
         layout.next(card);
        // TODO add your handling code here:
    }//GEN-LAST:event_copyrightButtonActionPerformed

    private void screenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenButtonActionPerformed
         ArrangeScreeningPanel panel=new ArrangeScreeningPanel(card, business, userAccount);
         card.add("ArrangeScreeningPanel",panel);
         CardLayout layout=(CardLayout)card.getLayout();
         layout.next(card);
        // TODO add your handling code here:
    }//GEN-LAST:event_screenButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton copyrightButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton screenButton;
    // End of variables declaration//GEN-END:variables
}
